name: Build, Test en Deploy .NET Core WebApi naar Azure App Service (ZIP-deploy)

env:
  ARTIFACT_NAME: WebApi
  DOTNET_CORE_VERSION: 10.0.x
  PUBLISH_DIRECTORY: "./out/publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check AZURE_WEBAPP_NAME secret
        env:
          super_secret: ${{ secrets.AZURE_WEBAPP_NAME }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "Het repository secret 'AZURE_WEBAPP_NAME' bestaat niet."
          exit 1

      - name: Check WEBAPI_PROJECT_NAME secret
        env:
          super_secret: ${{ secrets.WEBAPI_PROJECT_NAME }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "Het repository secret 'WEBAPI_PROJECT_NAME' bestaat niet."
          exit 1

      - name: Check AZURE_WEBAPP_PUBLISH_PROFILE secret
        env:
          super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "Het repository secret 'AZURE_WEBAPP_PUBLISH_PROFILE' bestaat niet."
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./${{ secrets.WEBAPI_PROJECT_NAME }} --output ${{ env.PUBLISH_DIRECTORY }} --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

  deploy:
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - name: Download artifact van build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_DIRECTORY }}

      - name: Zip publish folder
        run: zip -r deploy.zip ${{ env.PUBLISH_DIRECTORY }}

      - name: Deploy naar Azure via ZIP-deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'deploy.zip'